version: '3'
services:
  firefly_iii_client_generator:
    build:
      context: .
      args:
        - OPENAPI_TAG=v6.2.1
    volumes:
      - ./target:/build/target
      - .:/build/src:ro
      - ./.generator:/generator
    environment:
      API_VERSION: 1.5.6
